### ISSUE TITLE
bug: can't run image "debian:jessie"

### ISSUE THREAD

**Issue by tianyin** [tianyin/rekcod#9]
@cutylewiwi I run `debian:jessie` and see the following exceptions
```
$ python run_fsaudit.py
```
```
Traceback (most recent call last):
  File "run_fsaudit.py", line 33, in <module>
    fsprint('debian:jessie')
  File "run_fsaudit.py", line 21, in fsprint
    md5map = imageaudit(image)
  File "/home/tianyin/rekcod/fsaudit/fsaudit.py", line 11, in imageaudit
    container = client.containers.get(image + "-c")
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 723, in get
    resp = self.client.api.inspect_container(container_id)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 748, in inspect_container
Error response from daemon: No such container: debian:jessie-c
Error: failed to start containers: debian:jessie-c
    self._get(self._url("/containers/{0}/json", container)), True
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("No such container: debian:jessie-c")
```

I don't understand why you add a "-c" as the prefix? Can you fix the problem?

**Comment by tianyin** [comment]
what I don't understand is why you append a dash c in here, which caused the problem.

~t

**Comment by tianyin** [comment]
···
Error response from daemon: Invalid container name (debian:jessie-c), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
···
